set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB,xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -g allow-passthrough on
set -s extended-keys always
set-environment -g COLORTERM truecolor

set -g mouse on
set -g set-clipboard on
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"

bind Left  if-shell "$is_vim" 'send-keys C-w Left'  'select-pane -L'
bind Down  if-shell "$is_vim" 'send-keys C-w Down'  'select-pane -D'
bind Up    if-shell "$is_vim" 'send-keys C-w Up'    'select-pane -U'
bind Right if-shell "$is_vim" 'send-keys C-w Right' 'select-pane -R'

bind-key -T prefix -r C-Left  resize-pane -L 5
bind-key -T prefix -r C-Right resize-pane -R 5
bind-key -T prefix -r C-Up    resize-pane -U 5
bind-key -T prefix -r C-Down  resize-pane -D 5

set -g status-position top

set -g status-style 'bg=#0d0c0c,fg=#c5c9c5'
set -g message-style 'fg=#8ea4a2,bg=#282727,align=centre'
set -g message-command-style 'fg=#8ea4a2,bg=#282727,align=centre'
set -g mode-style 'bg=#282727,bold'
set -g clock-mode-colour '#8ba4b0'
set -g window-status-activity-style 'bg=#8992a7,fg=#0d0c0c'
set -g window-status-bell-style 'bg=#c4b28a,fg=#0d0c0c'

set -g window-status-format '#[fg=#a6a69c,bg=#0d0c0c]#[fg=#0d0c0c,bg=#a6a69c]#I#[fg=#c5c9c5,bg=#282727] #W#{?window_activity_flag, 󱅫,}#{?window_bell_flag, 󰂞,}#{?window_silence_flag, 󰂛,}#{?window_active, 󰖯,}#{?window_last_flag, 󰖰,}#{?window_marked_flag, 󰃀,}#{?window_zoomed_flag, 󰁌,} #[fg=#282727,bg=#0d0c0c]'
set -g window-status-current-format '#[fg=#8ba4b0,bg=#0d0c0c]#[fg=#0d0c0c,bg=#8ba4b0]#I#[fg=#c5c9c5,bg=#393836] #W#{?window_activity_flag, 󱅫,}#{?window_bell_flag, 󰂞,}#{?window_silence_flag, 󰂛,}#{?window_active, 󰖯,}#{?window_last_flag, 󰖰,}#{?window_marked_flag, 󰃀,}#{?window_zoomed_flag, 󰁌,} #[fg=#393836,bg=#0d0c0c]'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'
if "test ! -d ~/.tmux/plugins/tpm" \
  "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm'"
run '~/.tmux/plugins/tpm/tpm'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left '  #{?client_prefix,#[fg=#8992a7]● ,  }'
set -g status-right '#[fg=#0d0c0c,bg=#{?client_prefix,#c4746e,#87a987}] #[fg=#c5c9c5,bg=#282727] #S '
set -ag status-right '#[fg=#0d0c0c,bg=#b6927b] #[fg=#c5c9c5,bg=#282727] #{b:pane_current_path} '
set -ag status-right '#[fg=#0d0c0c,bg=#8ea4a2]󰃰 #[fg=#c5c9c5,bg=#282727] %Y-%m-%d %H:%M '
